peertube.settings:
  type: config_object
  label: 'Peertube settings'
  mapping:
    oembed_providers_url:
      type: uri
      label: 'The URL of the default oEmbed providers database in JSON format'
    peertube_instances:
      type: text
      label: 'The domain names of the used PeerTube instances.'